SELECT R1.FOOD_TYPE, R1.REST_ID, R1.REST_NAME, R1.FAVORITES
FROM REST_INFO AS R1
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS R2
ON R1.FOOD_TYPE = R2.FOOD_TYPE AND R1.FAVORITES = R2.MAX_FAVORITES
ORDER BY FOOD_TYPE DESC
