-- 코드를 입력하세요
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS AS I
WHERE I.SEX_UPON_INTAKE LIKE "Intact%" 
AND I.ANIMAL_ID IN (
    SELECT O.ANIMAL_ID
    FROM ANIMAL_OUTS AS O
    WHERE O.SEX_UPON_OUTCOME NOT LIKE "Intact%" 
)
ORDER BY ANIMAL_ID;