SELECT F1.ID, F3.FISH_NAME, F1.LENGTH
FROM FISH_INFO F1
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    WHERE LENGTH IS NOT NULL
    GROUP BY FISH_TYPE
) AS F2
ON F1.FISH_TYPE = F2.FISH_TYPE AND F1.LENGTH = F2.MAX_LENGTH
JOIN FISH_NAME_INFO AS F3
ON F1.FISH_TYPE = F3.FISH_TYPE
ORDER BY F1.ID